"""empty message

Revision ID: 645c2b0e3543
Revises: a804bed878f7
Create Date: 2021-08-20 20:14:03.421220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645c2b0e3543'
down_revision = 'a804bed878f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('ventas_productos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'ventas_productos')
    # ### end Alembic commands ###
