"""empty message

Revision ID: 9b61d7e1089a
Revises: 04a0c887fcae
Create Date: 2021-10-26 15:05:27.148675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b61d7e1089a'
down_revision = '04a0c887fcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('rol', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'rol')
    # ### end Alembic commands ###
